name: Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node-version:
        required: true
        type: string

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  test:
    permissions:
      checks: write
      contents: read
    name: Run tests on Node v${{ inputs.node-version }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup workspace ⚙️
        uses: ./.github/actions/setup-workspace
        with:
          os: ${{ inputs.os }}
          node-version: ${{ inputs.node-version }}

      - name: Build 🔧
        run: |
          npm run build
          npm run postbuild

      - name: Run tests 🧪
        run: npx jest --maxWorkers=100% -c=jest.config.ts
        env:
          CI: true
          DISABLE_MOCKED_WARNING: true

      - name: Run e2e tests 🧪
        run: |
          npx jest --maxWorkers=100% -c=jest-e2e-cjs.config.ts --no-cache
          node --experimental-vm-modules --no-warnings node_modules/jest/bin/jest.js --maxWorkers=100% -c=jest-e2e-esm.config.ts --no-cache

      - name: Run tests in example projects 🧪
        run: npm run test-examples
